import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useCallback, useEffect, useRef } from 'react'
import Spinner from '../src/components/spinner'
import { useDogs } from '../src/hooks/use-dogs'
import useIntersectionObserver from '../src/hooks/use-intersection-observer'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [dogs, loading, setPage] = useDogs();
  const externalRef = useRef();
  const {isIntersected} = useIntersectionObserver({
    // externalRef: loading ? null : externalRef,
    externalRef: externalRef,
    once: false
  })

  useEffect(() => {
    if(!isIntersected) return;
    setPage((prevPage: number) => prevPage + 1);
  }, [isIntersected, setPage]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Dogs breed App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <span>Dogs breed App!</span>
        </h1>

        <p className={styles.description}>
          Add <Link href='/add-dog'>new dog</Link>
        </p>

        <div className={styles.grid}>
          {
            dogs && dogs.map((dog: any) => 
              <div className={styles.card} key={dog.id}>
                <div className={styles.cardimage}>
                  <Image src={dog.photoUrl} alt={dog.breedName} layout="fill" objectFit='contain' />
                </div>
                <h2>[{dog.id}] {dog.breedName}</h2>
                {/* <p>Find in-depth information about Next.js features and API.</p> */}
              </div>
            )
          }
          
          {
            loading && <Spinner/>
          }

        </div>
        <div id="bottom" ref={externalRef}></div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
