version: "3.7"

networks:
  app-network:
    driver: bridge

services:
  db:
    build: ./database
    image: mysql:8.0
    container_name: ${MYSQL_HOST}
    volumes:
      - ./database/data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    expose:
      - ${MYSQL_PORT}
    environment:
      MYSQL_TCP_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    networks:
      - app-network

  main:
    container_name: dogs-api
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network
